config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: {minimum:6, maximum:100}
    validates :description, presence: true, length: {minimum:10, maximum:300}
    belongs_to :user
    private
        
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_many :articles
    belongs_to :user_role
    validates :name, presence: true, uniqueness: { case_sensitive: false }, length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false }, length: {minimum: 3 , maximum: 25}, format: { with: VALID_EMAIL_REGEX }

    has_many :articles
    has_secure_password

    
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
    self.table_name = "user_role"
    has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user
    def current_user
        @current_user ||= User.find([session[:user_id]]) if session[:user_id]
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    def show
    end
    
    def index
        @articles = Article.paginate(page: params[:page], per_page: 30)
    end
    
    def new
        @article = Article.new
    end
    
    def create
        @article = Article.new(article_params)
        @article.user = User.first
        if @article.save
            flash[:notice] = "Article was created successly."
            redirect_to article_path(@article)
        else 
            render 'new'
        end
    end

    def edit
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article was edited"
            redirect_to @article
        else 
            render 'edit'
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end
    
    private 

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end
    

    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
      
    def about
    
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            flash[:notice] = "Logged in successly"
            session[:user_id] = user.id
            redirect_to user
        else 
            flash.now[:alert] = "There was something wrong with your login details"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end
    
    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:notice] = "Welcome to alpa Blog #{user.name}."
        session[:user_id] = user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    debugger
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      @articles = @user.articles.paginate(page: params[:page], per_page: 30)
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "rounded shadow mx-auto d-block")
    end


    def logged_in?
        !!current_user
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
 <% @articles.each do |article| %>
 <div class="row justify-content-md-center">
  <div class="col-8 mt-4">
<div class="card text-center">
  <div class="card-header font-italic">
  <% if article.user %>
    by <%=  link_to article.user.name, user_path(article.user) %>
  <% end %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= link_to  article.title, article_path(article), class: "text-success" %></h5>
    <p class="card-text"><%= truncate(article.description, length:100 )%></p>
    <%= link_to  "View", article_path(article), class: "btn btn-outline-success" %>
    <%= link_to  "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
    <%= link_to  "Delete", article_path(article),  method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-outline-danger" %>
  </div>
  <div class="card-footer text-muted">
    <small>Created <%= time_ago_in_words(article.created_at) %> Ago,
    Edited <%= time_ago_in_words(article.updated_at)%></small>
  </div>
</div>
</div>
</div>
<% end %>

app/views/articles/_form.html.erb
<div class="container">
 <%= render 'shared/form', obj: @article%>
<%= form_with(model: @article, local: true, class: "shadow p-3 mb-3 bg-info rounded") do |f|  %>
 <div  class="form-group row">

   <%= f.label :title, class: "col-2 col-form-label" %>
   <div class="col-10">
   <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
   </div>
 </div>
 <div class="form-group row">
   <%= f.label :description, class:"col-2 col-form-label" %>
   <div class="col-10">
   <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of title" %>
   </div>
   </div>
  <div class="form-group row justify-content-center">
   <%= f.submit class: "btn btn-success btn-lg" %>
  </div>
<% end %>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">listing all articles</h1>

<div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
</div><%= render 'article' %>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">New Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4"><%= @article.title%></h1>
 <div class="row justify-content-md-center">
  <div class="col-8 mt-4">
<div class="card text-center">
  <div class="card-header font-italic">
  <% if @article.user %>
    by <%  link_to @article.user.name, user_path(@article.user) %>
    <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
  <% end %>  
  </div>
  <div class="card-body">
    <p class="card-text text-left"><%= @article.description %></p>
    <%= link_to  "View", article_path(@article), class: "btn btn-outline-success" %>
    <%= link_to  "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
    <%= link_to  "Delete", article_path(@article),  method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-outline-danger" %>
  </div>
  <div class="card-footer text-muted">
    <small>Created <%= time_ago_in_words(@article.created_at) %> Ago,
    Edited <%= time_ago_in_words(@article.updated_at)%></small>
  </div>
</div>
</div>
</div>


<%= link_to 'Return to articles listing', articles_path %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
 <div class="container text-center">
  <small>Copyright &copy; <%= link_to "Igor Matheus", "https://github.com/igorkafka"%>
 </div>
</footer>

app/views/layouts/_messages.html.erb
   <div class="container">
   <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
     <%= msg%>
     </div>
       <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
   <% end %>
   </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to  "Users", users_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to  "Create New Article", new_article_path, class: "dropdown-item" %>
          <%= link_to  "View Articles", articles_path, class: "dropdown-item" %>
        </div>
      </li>

      <% if logged_in? %>
      <li class="nav-item">
         <%= link_to current_user.name, user_path(current_user), class: "nav-link", method: :delete %>
      </li>
      <li class="nav-item">
         <%= link_to  "Log out", logout_path, class: "nav-link", method: :delete %>
      </li>
      <% else %>
       <li class="nav-item">
         <%= link_to  "Log in", login_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <div class="page-content">
     <%= render 'layouts/messages' %>
    <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center">
    <h1 class="display-4">Bootstrap Tutorial</h1>      
    <p>Bootstrap is the most popular HTML, CSS, and JS framework for developing responsive, mobile-first projects on the web.</p>
    <p><%= link_to "Sign up!", new_user_path, class: "btn btn-success"%></p>
  </div> 
</div>

app/views/shared/_form.html.erb
<% if obj.errors.any? %>
 <div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase%> from saved</h2>
 <ul>
  <% obj.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
 <%= render 'shared/form', obj: @user %>
<%= form_with(model: @user, local: true, class: "shadow p-3 mb-3 bg-info rounded") do |f|  %>
 <div  class="form-group row">

   <%= f.label :name, class: "col-2 col-form-label" %>
   <div class="col-10">
   <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "name of User" %>
   </div>
 </div>
 <div class="form-group row">
   <%= f.label :email, class:"col-2 col-form-label" %>
   <div class="col-10">
   <%= f.text_field :email, class: "form-control shadow rounded", placeholder: "Enter your email adress" %>
   </div>
   </div>
 <div class="form-group row">
   <%= f.label :password, class:"col-2 col-form-label" %>
   <div class="col-10">
   <%= f.password_field :password,  class: "form-control shadow rounded", placeholder: "Choose a password" %>
   </div>
   </div>
  <div class="form-group row justify-content-center">
   <%= f.submit @user.new_record? ? "Sign Up": "Update account", class: "btn btn-outline-light btn-lg" %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
    <%= will_paginate @users, :container => false %>
<h1 class="text-center mt-4">Alpha Bloggers</h1>

 <% @users.each do |user| %>
 <div class="row justify-content-md-center">
  <div class="col-8 mt-4">
<div class="card text-center">
  <div class="card-header font-italic">
     <%= link_to user.name, user  %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= link_to gravatar_for(user), size: 150%></h5>
    <p class="card-text"><%= pluralize(user.articles.count, "Article") %></p>
    <%= link_to  "View profile", user, class: "btn btn-outline-success" %>
    <%= link_to  "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
  </div>
  <div class="card-footer text-muted">
    <small>Joined <%= time_ago_in_words(user.created_at) %> Ago
  </div>
</div>
</div>
</div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.name%>'s profile</h1>

<%= gravatar_for @user, size: 200%>
<div class="text-center mt-4">
 <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info"%>
</div>

<h3 class="text-center mt-4">listing all articles</h3>
<div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
<%= render 'articles/article' %>